export const marioTennisModals = [
    {
        'id':   'marioTennis64',
        'img':  'Mario_Tennis64',
        'content': `          
                    <p><strong>Mario Tennis</strong> é uma marca de jogos esportivos que apresenta partidas de tênis incorporando personagens, temas e locais da franquia Super Mario. Embora precedida por vários jogos de tênis anteriores com o personagem Mario, a série foi criada para a Nintendo por seu parceiro Camelot Software Planning (que também criou a série Mario Golf) e teve sua primeira parcela no console Nintendo 64 em 2000. Desde a série fez sua estreia, cada geração sucessiva apresentou um console e uma versão portátil. O primeiro jogo da série Mario Tennis foi o segundo projeto desenvolvido pela Camelot para um sistema Nintendo, e teve três sequências no total (com o jogo original e a primeira sequência tendo contrapartes nos respectivos companheiros portáteis de seus consoles).</p>

                    <p>Mario Tennis inclui variações de partidas de tênis compostas por personagens, quadras e cenários baseados na franquia Super Mario. A escolha das quadras varia, desde os três tipos de quadras de tênis padrão, até aquelas temáticas dos jogos Super Mario, que adotam os estilos estéticos dos jogos em que se baseiam e apresentam elementos temáticos que influenciam a forma como a partida será disputada. naquela superfície (alguns dos quais se manifestam como obstáculos que dificultam os movimentos dos personagens ou interferem de alguma forma na jogabilidade). Além do tênis padrão, Mario Tennis pode apresentar variantes do esporte que adotam diferentes regras e métodos de vitória.</p>

                    <p>O sistema de controle difere significativamente de outros videogames de tênis. Os chutes são executados pressionando um ou ambos os botões principais do controle, que fazem a bola girar de diferentes maneiras. Pressionar um botão duas vezes atinge a tacada de tênis com mais força e giro. Além disso, pressionar os dois botões em uma ordem diferente pode resultar em um tipo de chute totalmente diferente, como um lob ou um drop shot. Ambos os botões podem ser pressionados ao mesmo tempo para acertar um golpe muito poderoso. Quanto mais tempo um botão for pressionado antes do contato com a bola, mais forte será o chute. O sistema de controle permite que jogadores de todos os níveis se familiarizem com a mecânica do jogo em um tempo muito curto, ao mesmo tempo que incentiva os jogadores avançados a aproveitar a variedade de tacadas oferecidas para criar diferentes estratégias para ganhar pontos. Além dos movimentos genéricos do tênis, mais tarde a série começou a apresentar "Power Shots" especiais, movimentos únicos que incorporam as qualidades específicas dos personagens que os utilizam; O Power Tour os categoriza especificamente como chutes "ofensivos" (aqueles que fortalecem a bola e colocam vários efeitos colaterais nos jogadores com quem fazem contato) ou chutes "defensivos" (aqueles que anulam os efeitos secundários dos chutes ofensivos e alcançam as bolas que normalmente estaria fora de alcance).</p>

                    <p>Muitos modos de jogo apareceram ao longo da série Mario Tennis. O modo central de jogo é o "Modo Torneio", que compreende um conjunto de eventos com dificuldade acumulada, onde os jogadores disputam partidas de tênis em duplas ou individuais, precisando vencer dois jogos para ganhar um set, e desbloquear personagens jogáveis se terminarem com sucesso. . Outro modo importante de jogo é o "Modo de Exibição", onde até quatro jogadores podem jogar suas próprias partidas, com os jogadores podendo escolher oponentes para controle do computador e as condições da partida, como a dificuldade dos adversários, a quadra usada , e o número de games e sets necessários para vencer. Jogos posteriores introduziram modos como “Ring Shot”, onde os jogadores podem ganhar pontos acertando a bola através de anéis de tamanhos variados; “Item Battle”, onde os personagens usam itens baseados no universo Super Mario para interferir no jogo uns dos outros e ganhar vantagem; e minijogos especiais onde o jogador pode cumprir um objetivo relacionado ao tênis, incorporando temas de jogos anteriores da Nintendo.</p>

                    <p>Os jogos Mario Tennis apresentam uma seleção de personagens jogáveis da franquia Super Mario, incluindo Mario, Luigi, Princesa Peach, Princesa Daisy, Yoshi, Birdo, Wario, Waluigi, Donkey Kong, Bowser e vários outros. Os personagens são categorizados em seis grupos que refletem seu estilo de jogo: versátil, técnico, potência, velocidade, defensivo e astuto. Muitos dos personagens dos jogadores em Mario Tennis reaparecem como jogáveis ao longo das várias séries de spin-offs de Super Mario; às vezes, os jogos apresentam personagens para os quais um jogo de tênis marca suas primeiras aparições jogáveis, como Shy Guy e Wiggler. Para Waluigi, o Mario Tennis original foi sua primeira aparição, e para Daisy e Birdo, esse jogo marcou suas reintroduções e (no caso de Daisy) estabelecimento permanente no elenco recorrente da franquia Super Mario.</p>
                    `,
        'title': 'Mario Tennis (N64) - Nintendo VIP 24:7 Trailer',
        'video': 'https://www.youtube.com/embed/kGIywKq4neA'
    },
    {
        'id':   'marioPowerTennis',
        'img':  'Mario_Power_Tennis',
        'content': `          
                    <p><strong>Mario Power Tennis</strong> é um jogo de esportes para Nintendo GameCube e um relançamento para Wii (através da série New Play Control!). É a terceira parcela direta da série Mario Tennis e a continuação de Mario Tennis para Nintendo 64. Neste jogo, Mario e seus vários amigos e inimigos se encontram para jogar tênis. Como nos títulos esportivos anteriores do Super Mario, todos os personagens jogáveis têm Power Shots incrivelmente poderosos. Além disso, existem quadras no jogo que possuem efeitos e eventos especiais durante o jogo. Para cada quadra, também existem jogos especiais para jogar.</p>

                    <p>The game's opening begins with Mario and Luigi playing a match against Wario and Waluigi. The Mario Bros. win the match and celebrate as Wario and Waluigi complain about their loss. Bowser is seen surveying the match through hidden cameras. The next day, Wario and Waluigi see a picture of Mario and Luigi on the "Peach Dome Tournament" board and are angry to see that their opponents have knocked them out of the running. Wario and Waluigi vandalize the picture of Mario and Luigi, but the police pursues to arrest them. Wario and Waluigi escape into a janitor's closet, but they fall into what appears to be a training room. Bowser approaches them and offers an alliance to get revenge against the Mario Bros. After hours of training and seeing others playing their tennis matches, they carry out a plan to attack the final tournament match later that evening at the Peach Dome.</p>

                    <p>A abertura do jogo começa com Mario e Luigi jogando uma partida contra Wario e Waluigi. Os Mario Bros. vencem a partida e comemoram enquanto Wario e Waluigi reclamam da derrota. Bowser é visto monitorando a partida através de câmeras escondidas. No dia seguinte, Wario e Waluigi veem uma foto de Mario e Luigi no tabuleiro "Peach Dome Tournament" e ficam furiosos ao ver que seus oponentes os tiraram da corrida. Wario e Waluigi vandalizam a foto de Mario e Luigi, mas a polícia tenta prendê-los. Wario e Waluigi escapam para o armário de um zelador, mas caem no que parece ser uma sala de treinamento. Bowser se aproxima deles e oferece uma aliança para se vingar dos Mario Bros. Depois de horas de treinamento e de ver outros jogando suas partidas de tênis, eles executam um plano para atacar a partida final do torneio mais tarde naquela noite no Peach Dome.</p>

                    <p>Quando Mario e Luigi estão prestes a jogar a partida final do torneio contra Yoshi e Donkey Kong, Bowser aparece em um dirigível em forma de dirigível e prepara o torneio para que Wario e Waluigi possam ter sua revanche contra os Mario Bros., chocando o público. anfitriões do torneio, Princess Peach e Toadsworth. Todos ficam bravos com Wario, Waluigi e Bowser querendo que eles saiam, mas Wario e Waluigi os silenciam montando uma máquina que dispara Bob-ombs no Mario Bros. Bowser, enquanto isso, joga Bob-ombs neles. No entanto, Mario e Luigi desviam os Bob-ombs que se aproximam deles com suas raquetes de tênis. Outros personagens, como Diddy Kong e Koopa Troopa, são vistos brevemente ajudando os Mario Bros. a afastar os Bob-ombs enquanto os espectadores evacuam do estádio, correndo e gritando por suas vidas. Como último recurso, Bowser lança um Bullet Bill de seu dirigível contra eles, e Mario o repele com sua raquete, que dispara de volta e atinge o lançador Bob-omb de Wario. Waluigi está prestes a recuperar o lançador, mas Wario cai e o esmaga. O lançador, virado com a explosão, acidentalmente dispara uma Bob-omb no dirigível de Bowser, destruindo-o e revelando o estoque de Bob-ombs de Bowser abaixo de seu dirigível, chocando Peach, Toadsworth, Mario e Luigi.</p>

                    <p>O dirigível de Bowser começa a descer fora de controle e cai em direção a Wario e Waluigi. Wario e Waluigi tentam escapar, mas Bowser bate neles com os Bob-ombs a bordo, fazendo-os explodir com o impacto, criando uma grande explosão.</p>

                    <p>Depois, o trio fica inconsciente após a explosão, e seu plano de atacar Mario e seus amigos falhou completamente, apesar dos danos que causaram ao estádio. Mario e Luigi ficam aliviados e ilesos, e Mario quebra a quarta parede dizendo "Mama-mia" para a câmera antes que a cena termine.</p>
                    `,
        'title': 'Mario Power Tennis Trailer',
        'video': 'https://www.youtube.com/embed/gMmlxqYejik'
    },
    {
        'id':   'marioTennisPowerTour',
        'img':  'Mario_Tennis_Power_Tour',
        'content': `          
                    <p><strong>Mario Tennis: Power Tour</strong>, conhecido em línguas europeias como <strong>Mario Power Tennis</strong>, é o quarto jogo direto da série Mario Tennis e a contraparte do Game Boy Advance de Mario Power Tennis para o Nintendo GameCube. Este seria o lançamento final do Super Mario para o Game Boy Advance. É muito semelhante a Mario Tennis na jogabilidade e no enredo, embora tenha a adição de Power Shots. Embora seja a contrapartida de Mario Power Tennis, os dois jogos não podem ser conectados de forma alguma.</p>

                    <p>O jogo é compatível com o adaptador sem fio Game Boy Advance. O jogo foi relançado para o Virtual Console do Wii U no Japão em abril de 2014, na Europa e na Austrália em junho de 2014, e na América do Norte em julho de 2014.</p>

                    <p>O jogador, Clay ou Ace, é aluno da Royal Tennis Academy. Durante esse período, desafiantes mascarados chegam à academia e derrotam os campeões da academia, deixando todos incrédulos, pois nunca perderam antes. Determinados a descobrir quem são, Clay ou Ace passam a fazer parte da classe Junior, onde derrotam todos. Eles seguem para as classes Sênior e depois para o Varsity, onde descobrem que os dois melhores jogadores ou times do ranking avançam para o Island Open, onde jogariam contra os melhores alunos das outras três escolas de tênis.</p>

                    <p>Clay/Ace logo garantem sua entrada no Island Open. Eles ouvem um boato de que os vencedores do Open teriam a chance de jogar contra Mario. Durante o período do Open, o jogador pode desejar viajar entre a Academia e a área do Open a qualquer momento. Depois de vencer o Open, Clay e Ace percebem que ainda não descobriram quem são as jogadas mascaradas. Porém, no dia seguinte, Mario chega à Academia e dá a Clay/Ace a honra de jogar com eles. Assim começa o Torneio Peach, com Clay/Ace como jogadores. Em duplas, ambos são uma equipe. Clay e Ace viajam para o Reino do Cogumelo no Toad Express, onde os jogos acontecem no Peach Dome, de propriedade da Princesa Peach. Durante sua estada, Clay/Ace são informados de que Mario e companhia foram os jogadores mascarados da academia, e que também foram eles que introduziram o conceito de tiros poderosos na Terra. Piantas, Toads e Nokis estão presentes na cúpula como parte do público. Vencer o jogo desbloqueará a dificuldade técnica, o que aumenta o nível de habilidade dos personagens no modo história. Vencer este modo recompensará o jogador com uma tela com todos os personagens que Ace ou Clay venceram em sua jornada.</p>
                    `,
        'title': 'Mario Tennis Power Tour Game Boy Gameplay - E3 2005',
        'video': 'https://www.youtube.com/embed/ZEZcGnVN17s'
    },
    {
        'id':   'marioTennisOpen',
        'img':  'Mario_Tennis_Open',
        'content': `          
                    <p><strong>Mario Tennis Open</strong> é um jogo de esportes para Nintendo 3DS e o quinto jogo direto da série Mario Tennis (desenvolvida pela Camelot Software Planning). O jogo conta com suporte para giroscópio e multijogador online (usando os procedimentos da Nintendo Network). Esta é a primeira parcela portátil da série a não incluir um Modo História ou elementos de RPG e a primeira parcela portátil com um modo Torneio. Este jogo também é o primeiro jogo Super Mario a usar códigos QR (Quick Response). Neste caso, é usado para desbloquear personagens jogáveis e a fantasia de Yoshi. O jogo requer blocos de 2019 para download na Nintendo eShop.</p>

                    <p>A jogabilidade apresenta os elementos básicos tradicionais dos jogos Mario Tennis anteriores. Para vencer, o jogador deve somar pontos acertando a bola para o outro lado da quadra e quicando duas vezes, objetivo básico do tênis. Os jogadores ganham 15 pontos para cada arremesso bem-sucedido e podem vencer o jogo ganhando pontos de set, jogo e partida ao ganhar 60 pontos em cada jogo. O número de sets e jogos pode ser alterado pelo jogador no modo exibição, mas não no modo torneio.</p>

                    <p>Este jogo utiliza os botões do 3DS durante partidas single ou multiplayer, embora os jogadores possam realizar diversas tacadas de tênis selecionando os painéis de tacadas na tela sensível ao toque, que acenderão para alertar o jogador sobre a melhor tacada a ser usada em uma determinada situação. Ao segurar o 3DS verticalmente, os jogadores podem fazer uso do já mencionado suporte de giroscópio, desativando a funcionalidade 3D. Isso coloca a câmera atrás de seu personagem, cujo movimento se torna automático, e permite que os jogadores controlem a direção de seus disparos com base na posição do console. O suporte ao giroscópio pode ser desativado segurando o console horizontalmente ou desativando-o no menu Opções. Existem também Modos Especiais no jogo, como o “Super Mario Tennis”, onde o jogador precisa acertar inimigos, blocos e moedas com bolas de tênis em alguns níveis de Super Mario Bros.</p>
                    `,
        'title': 'Mario Tennis Open - Special Games Trailer',
        'video': 'https://www.youtube.com/embed/kQ0S3r98iDI'
    },
    {
        'id':   'marioTennisUltraSmash',
        'img':  'Mario_Tennis_Ultra',
        'content': `          
                    <p><strong>Mario Tennis: Ultra Smash</strong> é um jogo de esportes multijogador da série Mario Tennis, desenvolvido pela Camelot Software Planning, para Wii U. É o terceiro console doméstico da série e o sétimo no geral. Foi lançado pela primeira vez em 20 de novembro de 2015 na Europa e na América do Norte. Até quatro jogadores podem jogar localmente, enquanto até dois jogadores também podem usar seus recursos online para jogar com outras pessoas ao redor do mundo.

                    <p>O jogo, como uma parcela da franquia Mario Tennis, apresenta uma jogabilidade tradicional de tênis com vários elementos da franquia Super Mario misturados, como os personagens jogáveis e os truques introduzidos nas quadras. Ele mantém vários elementos de dois antecessores, Mario Power Tennis e Mario Tennis Open, ao mesmo tempo que introduz Mega Battles e Jump Shots; Mega Battle é um modo onde os jogadores podem crescer pegando Mega Mushrooms para aumentar suas capacidades ofensivas e defensivas, enquanto Jump Shots permite que os jogadores saltem no ar para realizar golpes mais poderosos. O Wii U GamePad é aproveitado para dois jogadores individuais, permitindo que um segundo jogador use uma tela separada para a perspectiva de seu personagem. Se os jogadores baixarem o jogo da Nintendo eShop, o software exigirá 888 MB para ser instalado. O jogo também oferece suporte a amiibo, permitindo aos jogadores usar amiibo compatíveis para treinar e jogar com um personagem controlado pela CPU.</p>

                    <p>O jogo é jogado de forma semelhante às entradas anteriores da série Mario Tennis e segue as regras básicas do tênis. Os jogadores sacam e batem a bola para frente e para trás até que um dos lados erre a bola. Os jogadores ganham 15 pontos para cada arremesso bem-sucedido e ganham um ponto de jogo se um jogador marcar no 40º ponto. Se os jogadores empatarem após a marca de 40 pontos, um empate começa e qualquer um dos jogadores deve marcar dois pontos consecutivos para ganhar um ponto de jogo. Ganhar vários pontos de jogo torna o jogador vitorioso em um set ou partida. As partidas podem ser divididas em sets. Se dois jogadores empatarem em um set, começa o desempate, onde um jogador deve atingir sete pontos para vencer o set ou partida.</p>

                    <p>Os jogadores podem usar o Wii U GamePad, o Wii Pro Controller ou o Wii Remote na lateral para jogar. O jogo não suporta controles de movimento para o Wii Remote, então o Wii Remote na lateral é a única opção de controle para ele.</p>

                    <p>O jogo funciona com amiibo. Quando um amiibo compatível é digitalizado para o jogo, esse personagem aparece no jogo como um parceiro de computador que pode ser treinado, semelhante ao Super Smash Bros. para Nintendo 3DS/Wii U. Após cada cinco partidas no Knockout Challenge, ele ganha um amiibo aleatório. aumento de estatísticas, e o personagem amiibo pode obter 10 no total. Os jogadores podem acessar o menu de treinamento amiibo para alterar as estatísticas, gastando moedas para alterar os slots de estatísticas. Os parceiros amiibo tornam possível jogar partidas 2 contra 1, embora apenas com oponentes CPU, tornando-o o primeiro e único jogo Mario Tennis onde partidas 2 contra 1 são possíveis.</p>

                    <p>Ao contrário de outras parcelas, Mario Tennis: Ultra Smash não oferece uma opção para canhotos.</p>
                    `,
        'title': 'Mario Tennis: Ultra Smash - &#39;Love-All&#39; Game Trailer',
        'video': 'https://www.youtube.com/embed/twANJkKEoH4'
    },
    {
        'id':   'marioTennisAces',
        'img':  'Mario_Tennis_Aces',
        'content': `          
                    <p><strong>Mario Tennis Aces</strong> é um jogo de esportes multijogador para Nintendo Switch e o oitavo episódio da série Mario Tennis. É também o primeiro jogo da série desde Mario Tennis: Power Tour no Game Boy Advance a apresentar um modo de história, no qual Mario deve avançar através de uma série de missões e impedir que uma poderosa raquete de tênis, Lucien, destrua o Reino de Bask, o cenário do jogo. Embora o mecanismo de jogo pareça ser baseado no de Mario Tennis: Ultra Smash, ele introduz novas técnicas à jogabilidade de tênis tradicional da série. Uma das principais características deste jogo é um medidor de energia que pode ser carregado durante a partida, movimentando a bola. A energia concede a capacidade de desacelerar o tempo durante uma partida para pegar a bola com mais facilidade. Sob certas condições, também pode ser usado para parar o tempo e lançar a bola de uma perspectiva de primeira pessoa para o outro lado da quadra através de Zone Shots e Special Shots. São tipos de golpes poderosos que podem danificar ou quebrar a raquete do oponente se não forem combatidos corretamente.</p>

                    <p>O jogo também oferece recursos online expandidos, principalmente por meio de torneios e desafios cooperativos, onde os jogadores podem participar para desbloquear conteúdo exclusivo. Desde o lançamento, o jogo foi atualizado com novos personagens jogáveis, níveis de modo de história, modos de jogo e recursos de torneio, principalmente uma classificação de classificação.</p>

                    <p>Tal como num jogo de ténis, os jogadores têm de rebater a bola para a frente e para trás até que um dos lados a erre. Em partidas normais, os jogadores que acertam o chute marcam 15 pontos; aos 40 pontos, os jogadores ganham um ponto de jogo e precisam marcar outra tacada bem-sucedida para vencer o jogo. Um empate começa se ambos os lados estiverem empatados em 40 pontos, onde precisam marcar uma vantagem de dois pontos para vencer o jogo. São dois jogos em um set, com o número de sets dependendo das regras da partida. Um desempate é usado para resolver a partida se os jogadores estiverem constantemente empatados durante a partida. No desempate, os jogadores marcam um ponto para cada arremesso bem-sucedido. São necessários sete pontos para vencer o desempate e, por extensão, a partida. Se os jogadores obtiverem um empate de 6 pontos, eles precisam de uma vantagem de dois pontos para vencer.</p>

                    <p>As partidas podem ser disputadas em simples, envolvendo apenas dois jogadores, ou em duplas, envolvendo duas duplas de jogadores. Em cada partida, há um sacador e um recebedor, que trocam de lado no início de cada jogo. O sacador deve lançar a bola no lado oposto da quadra, caso contrário será falta. Duas faltas consecutivas (falta dupla) farão com que o adversário marque. A velocidade da bola é exibida brevemente na parte superior da tela quando ela é sacada. A bola tem que ficar dentro dos limites do campo; se cair fora, o adversário marcará. Acertar a bola nas laterais da quadra tem o mesmo efeito nas partidas de simples, mas é permitido nas duplas.</p>
                    `,
        'title': 'Mario Tennis Aces - First Gameplay Trailer',
        'video': 'https://www.youtube.com/embed/qYcAdMSV29Y'
    }
]

